disabled_rules:
- comma
- colon
 
opt_in_rules:
- empty_count
- empty_string
- private_action
- weak_delegate
- toggle_bool
- unused_import
 
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
- EBless/Utilities/ThirdParty/SwiftyJSON.swift
 
line_length:
    warning: 500
    error: 2000
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
    ignores_interpolated_strings: true
 
function_body_length:
    warning: 300
    error: 500
 
function_parameter_count:
    warning: 10
    error: 20
 
type_body_length:
    warning: 300
    error: 500
 
file_length:
    warning: 500
    error: 800
    ignore_comment_only_lines: true
    
large_tuple: # warn user when using 5 values in tuple, give error if there are 6
   - 5
   - 6
   
identifier_name:
  allowed_symbols: "_"
  min_length: 2
  max_length:
    warning: 90
    error: 1000
    
cyclomatic_complexity:
  ignores_case_statements: true
  warning: 50
  error: 60
  
trailing_newline:
  warning: 5
  
trailing_comma:
  mandatory_comma: false

custom_rules:
  open_iboutlets:
    included: ".*.swift"
    name: "IBOutlet opening"
    regex: '@IBOutlet ?(weak){0,1} var'
    message: "IBOutlet should be private"
    severity: error

reporter: "xcode"


